/* 
 * Tripartie Web API
 *
 * This document describes all use cases offered by the Tripartie Web API.<br /><br /> The Tripartie Web API allows you to easily create Transaction templates.<br /> A Transaction template allows a User (the Buyer) to safely initiate a Transaction pre-configured by another User (the Seller).<br /> This allows you to add a Secured Payment button on your website pages.<br /><br /> To facilitate working with the Web API, we built libraries for common development environment:<br/> <ul class=\"bullet\">   <li><a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/tripartie/webapi-jsclient\">Javascript</a></li> </ul> <br/> You're reading the documentation for version 1.0 of the Web API.<br/> Go to version <select id=\"version-switcher\"></select> 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@tripartie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TripartieWebAPI.CSharpClient.Api;
using TripartieWebAPI.CSharpClient.Model;
using TripartieWebAPI.CSharpClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TripartieWebAPI.CSharpClient.Test
{
    /// <summary>
    ///  Class for testing ModelTransactionTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelTransactionTemplateTests
    {
        // TODO uncomment below to declare an instance variable for ModelTransactionTemplate
        //private ModelTransactionTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelTransactionTemplate
            //instance = new ModelTransactionTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelTransactionTemplate
        /// </summary>
        [Test]
        public void ModelTransactionTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ModelTransactionTemplate
            //Assert.IsInstanceOf(typeof(ModelTransactionTemplate), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Permalink'
        /// </summary>
        [Test]
        public void PermalinkTest()
        {
            // TODO unit test for the property 'Permalink'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'SellerExternalId'
        /// </summary>
        [Test]
        public void SellerExternalIdTest()
        {
            // TODO unit test for the property 'SellerExternalId'
        }
        /// <summary>
        /// Test the property 'SellerTripartieId'
        /// </summary>
        [Test]
        public void SellerTripartieIdTest()
        {
            // TODO unit test for the property 'SellerTripartieId'
        }
        /// <summary>
        /// Test the property 'SubTotal'
        /// </summary>
        [Test]
        public void SubTotalTest()
        {
            // TODO unit test for the property 'SubTotal'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Flow'
        /// </summary>
        [Test]
        public void FlowTest()
        {
            // TODO unit test for the property 'Flow'
        }
        /// <summary>
        /// Test the property 'BuyerFees'
        /// </summary>
        [Test]
        public void BuyerFeesTest()
        {
            // TODO unit test for the property 'BuyerFees'
        }
        /// <summary>
        /// Test the property 'ShippingCosts'
        /// </summary>
        [Test]
        public void ShippingCostsTest()
        {
            // TODO unit test for the property 'ShippingCosts'
        }
        /// <summary>
        /// Test the property 'BuyerTotal'
        /// </summary>
        [Test]
        public void BuyerTotalTest()
        {
            // TODO unit test for the property 'BuyerTotal'
        }
        /// <summary>
        /// Test the property 'SellerFees'
        /// </summary>
        [Test]
        public void SellerFeesTest()
        {
            // TODO unit test for the property 'SellerFees'
        }
        /// <summary>
        /// Test the property 'SellerTotal'
        /// </summary>
        [Test]
        public void SellerTotalTest()
        {
            // TODO unit test for the property 'SellerTotal'
        }
        /// <summary>
        /// Test the property 'AdUrl'
        /// </summary>
        [Test]
        public void AdUrlTest()
        {
            // TODO unit test for the property 'AdUrl'
        }
        /// <summary>
        /// Test the property 'AllowPriceChange'
        /// </summary>
        [Test]
        public void AllowPriceChangeTest()
        {
            // TODO unit test for the property 'AllowPriceChange'
        }
        /// <summary>
        /// Test the property 'AllowInPerson'
        /// </summary>
        [Test]
        public void AllowInPersonTest()
        {
            // TODO unit test for the property 'AllowInPerson'
        }
        /// <summary>
        /// Test the property 'AllowDelivery'
        /// </summary>
        [Test]
        public void AllowDeliveryTest()
        {
            // TODO unit test for the property 'AllowDelivery'
        }
        /// <summary>
        /// Test the property 'HasPicture'
        /// </summary>
        [Test]
        public void HasPictureTest()
        {
            // TODO unit test for the property 'HasPicture'
        }

    }

}
